(prelude-require-packages '(
                          ace-window
                          paredit
                          ag
                          anzu
                          auto-complete
                          avy
                          window-number
                          evil
                          evil-leader
                          bind-key
                          browse-kill-ring
                          coffee-mode
                          color-theme-sanityinc-tomorrow
                          cyberpunk-theme
                          dash
                          diff-hl
                          diminish
                          dired-details
                          dired-single
                          discover-my-major
                          easy-kill
                          epl
                          expand-region
                          f
                          fill-column-indicator
                          flycheck
                          gist
                          git-timemachine
                          gitconfig-mode
                          gitignore-mode
                          god-mode
                          grizzl
                          guru-mode
                          helm
                          helm-swoop
                          inf-ruby
                          magit
                          move-text
                          operate-on-number
                          ov
                          projectile
                          ruby-end
                          ruby-refactor
                          scratch-palette
                          scss-mode
                          smart-mode-line
                          smartparens
                          ido-completing-read+
                          smartrep
                          undo-tree
                          volatile-highlights
                          workgroups
                          elisp-slime-nav
                          zenburn-theme
                          zop-to-char
                          ))




